# Generated by Django 5.0.4 on 2024-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='书名')),
                ('author', models.CharField(max_length=10, verbose_name='作者名')),
                ('info', models.CharField(blank=True, max_length=50, null=True, verbose_name='简介')),
            ],
        ),
    ]
