# Generated by Django 5.0.4 on 2024-05-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='book.category'),
        ),
    ]
